### ISSUE TITLE
Possible infinite loop with single byte input

### ISSUE THREAD

**Issue by pmezard** [rasky/go-lzo#1]
Hello,

I just ran go-fuzz on the decompressor and it found this possibly triggering an infinite loop:

  https://github.com/pmezard/go-lzo/blob/fuzz-it/crashers/5ba93c9db0cff93f52b521d7420e43f6eda2784f

with the fuzzer here:

  https://github.com/pmezard/go-lzo/blob/fuzz-it/fuzz.go

(I committed the corpus/ to the branch as well if you are interested).

I do not know if you implemented it just as an experiment or if you care about such reports.

**Comment by rasky** [comment]
Thanks I'll have a look. The straightforward decompressor just worked, but then I complicated it to optimize performance so I saw this coming... I was actually planning to try a fuzzer myself so thank you :)
