### ISSUE TITLE
Proposal to dual license the project

### ISSUE THREAD

**Issue by harshavardhana** [rasky/go-lzo#6]
Can this project be dual licensed? perhaps in Apache 2.0 or MIT such that Apache 2.0 projects can link against this library? 

Current LICENSE.gpl is too restrictive and incompatible with Apache 2.0 released projects.

**Comment by rasky** [comment]
No I'm sorry, it's not possible to dual-license it since I've faithfully converted the original C source code which is GPL so I don't feel I can change the license.

**Comment by harshavardhana** [comment]
Understood @rasky
